### ISSUE TITLE
Maps Error

### ISSUE THREAD

**Issue by dlaflotte** [mikesiegel/AncientAnguishMudlet#1]
First off great addition to Mudlet.  I'm looking to fix the maps.  Seem sI get a 
<[string "return map.eventHandler(...)"]:1: attempt to call field 'eventHandler' (a nil vaule)> error.  Any suggestions?  I have populated the aa.txt you load with the ascii art from the aa site but wondering if thats throwing the error or not.

**Comment by mikesiegel** [comment]
Thanks! I haven't been MUDing in a bit so I havent updated it recently. The mapping seems to work on my end, but I get a different error on debugging, an issue with some of the Geyser labels.  What version are you on?

Also, do you still have the generic_mapper 'Map script' on? In my profile I have it turned off. It's been a long time since I wrote the code but as far as I can tell, I don't use a map eventHandler. Basically the Mapper has functions, and they are all 'handled' by the code in the prompt triggers. I don't know if this is really a good way to do things but it works (?).

I did neglect to include the map! I'll fix that now. It's not exactly the map from the site, borders have been removed.

**Comment by dlaflotte** [comment]
Thanks for the response!  Yeah I do have the generic_mapper on.  I'll test that out and thanks for the map.  I'll check it out and do some debugging.

**Comment by mikesiegel** [comment]
k. I uploaded my copy of aa.txt. I might work on it a bit this weekend to clean it up (and perhaps get back into MUDing!). I had actually poked at it a few weeks ago because I wanted to do some streaming. If i recall the deleteLine functionality seemed to have changed a bit, and I think some issues with Geyser.

**Comment by dlaflotte** [comment]
Awesome I'll download the aa.text and test it out.  What streaming are you doing? other games?  Yeah been in AA since 95 and just came back.  So looking for a good client and addon :)

**Comment by dlaflotte** [comment]
also I see reference to this /map downloads/configs.lua.
is that lua supposed to be precreated?  I dont seem to have it.

**Comment by dlaflotte** [comment]
(sorry for all the comments).. Seems the map is fixed (aa.txt, disabling the default map handler, and reloading helped).  Still get the config error but not sure that matters.

**Comment by mikesiegel** [comment]
No worries, glad someone is looking at this! Been on AA since 92ish? the config.lua looks a generic mapper artifact..

https://github.com/mikesiegel/AncientAnguishMudlet/blob/ffce2f59a61dcf445b6e9e0ee931492c14c7ac9e/AA.xml#L1458

I gave up on the built in Mudlet mapper, and decided the static AA map was good enough. I was hoping one day to have it switch between world map and a town map once you were in a city but because the automapper gave me so much grief, the prospect of manually creating each city map was not too appealing.

The plan was to stream text games (including MUDs) but I've been mixing in whatever else I'm playing: https://www.twitch.tv/oldmanplaystextgames

**Comment by dlaflotte** [comment]
Cool thanks.  I'll close this issue out as it seems it was just the need for the aa.txt map.  I may dig into switching between town and global map.  That would be kinda neat.  
Also I'll have to check the stream.
Thanks again
